swagger: "2.0"
info:
  title: Documentación de la API de Productos
  version: 1.0.0
paths:
  /products:
    post:
      summary: Crea un nuevo producto
      tags:
        - Productos
      requestBody:
        $ref: "#/components/requestBodies/createProduct"
      responses:
        "201":
          description: Producto creado exitosamente
        "500":
          description: Error interno del servidor

  /user/products:
    get:
      summary: Obtiene los productos del usuario
      tags:
        - Productos
      responses:
        "200":
          description: Productos obtenidos exitosamente
        "500":
          description: Error interno del servidor

  /all-products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Productos obtenidos exitosamente
        "500":
          description: Error interno del servidor

  /products/delete/{id}:
    post:
      summary: Elimina un producto por su ID
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: ID del producto a eliminar
      responses:
        "200":
          description: Producto eliminado exitosamente
        "500":
          description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        owner:
          type: string
          default: admin
          description: Propietario del producto (por defecto, "admin")

  requestBodies:
    createProduct:
      description: Crea un nuevo producto
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
      example:
        title: "Producto de ejemplo"
        description: "Descripción del producto de ejemplo"
        price: 19.99
        thumbnail: "https://ejemplo.com/imagen.jpg"
        owner: "admin"
